version: "3.9"
name: beneficiaries-back-dev
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "1433:1433"
    networks:
      - beneficiaries
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    networks:
      - beneficiaries

networks:
  beneficiaries:
    name: beneficiaries-network-dev
    driver: bridge
