FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

ENV ACCEPT_EULA Y
ENV SA_PASSWORD Password#12345

COPY ./database/scripts .
COPY ./database/setup .

EXPOSE 1433

RUN sed -i 's/\r//' ./entrypoint.sh
RUN sed -i 's/\r//' ./setup-db.sh
RUN chmod +x entrypoint.sh

CMD /bin/bash ./entrypoint.sh
