version: "3.9"
name: beneficiaries-back-prod
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "1434:1433"
    networks:
      - beneficiaries
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8081:8080"
    networks:
      - beneficiaries

networks:
  beneficiaries:
    name: beneficiaries-network
    driver: bridge
